import './style.scss';
import './assets/developetra-mask.png';
import './assets/github.svg';
import './assets/linkedin.svg';
import './assets/instagram.svg';
import './assets/email.svg';
import './assets/arrow.svg';
import './assets/developetra-rose-mark.svg';
import './assets/android-chrome-192x192.png';
import './assets/android-chrome-512x512.png';
import './assets/apple-touch-icon.png';
import './assets/favicon.ico';
import './assets/favicon-16x16.png';
import './assets/favicon-32x32.png';
import './assets/mstile-150x150.png';
import './assets/placeholder-image.jpeg';
import './assets/developetra-logo.svg';
import './assets/peca-mark.svg';

import init from './js/init';
init.init();