import './style.scss';
import './assets/images/developetra-mask.png';
import './assets/images/github.svg';
import './assets/images/linkedin.svg';
import './assets/images/instagram.svg';
import './assets/images/email.svg';
import './assets/images/arrow.svg';
import './assets/images/developetra-rose-mark.svg';
import './assets/images/android-chrome-192x192.png';
import './assets/images/android-chrome-512x512.png';
import './assets/images/apple-touch-icon.png';
import './assets/favicon.ico';
import './assets/images/favicon-16x16.png';
import './assets/images/favicon-32x32.png';
import './assets/images/mstile-150x150.png';
import './assets/images/placeholder-image.jpeg';
import './assets/images/developetra-logo.svg';
import './assets/images/peca-mark.svg';
import './assets/images/developetra-primary-mark.png';
import './assets/images/copy.svg';
import './assets/images/book.svg';
import './assets/images/laptop.svg';

import init from './js/init';
init.init();